# Generated by Django 3.0.4 on 2020-03-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hayde',
            name='flight_name',
            field=models.CharField(default='abc', max_length=65),
        ),
    ]
