# Generated by Django 3.0.4 on 2020-03-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0003_auto_20200330_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.IntegerField(max_length=3),
        ),
    ]
