# Generated by Django 3.0.4 on 2020-04-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0007_auto_20200401_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
