# Generated by Django 3.0.4 on 2020-04-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0008_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='address1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='address2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobileno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='pin',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
