# Generated by Django 3.0.4 on 2020-04-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0009_auto_20200403_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobileno',
            field=models.TextField(default=0),
        ),
    ]
