# Generated by Django 3.0.4 on 2020-04-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0011_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobileno',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
